version: "3"
services:
  directus:
    image: directus/directus:11.3.5
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: buffet
      DB_USER: root
      DB_PASSWORD: "yourpassword"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*" # Replace with your frontend domain, e.g., "http://localhost:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: buffet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "yourpassword"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432